name: Test If

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest    
    steps:
      - name: init vars
        id: vars
        shell: bash        
        run: echo ::set-output name=FOO::${FOO}
  build:
    name: Testing if
    runs-on: ubuntu-latest
    needs: [init]
#    if: ${{ needs.init.steps.vars.outputs.HAS_SECRET }}
    steps:
      - run: echo ${{ needs.init.steps.vars.outputs.HAS_SECRET }}
