name: Test If

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest   
    outputs:
      output: ${{ steps.vars.outputs.HAS_CODECOV_TOKEN }} 
    steps:
      - name: Initialize workflow variables
        id: vars
        shell: bash
        run: |
          # check for CODECOV_TOKEN availability (work-around for inaccessible 'secrets' object for 'if'; see <https://github.community/t5/GitHub-Actions/jobs-lt-job-id-gt-if-does-not-work-with-env-secrets/m-p/38549>)
          unset HAS_CODECOV_TOKEN
          if [ -n "$CODECOV_TOKEN" ]; then HAS_CODECOV_TOKEN='true' else HAS_CODECOV_TOKEN='false' ; fi
          echo set-output name=HAS_CODECOV_TOKEN::${HAS_CODECOV_TOKEN}
          echo ::set-output name=HAS_CODECOV_TOKEN::${HAS_CODECOV_TOKEN}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
#       - name: init vars
#         id: vars
#         shell: bash        
#         run: echo ::set-output name=FOO::${{ secrets. }}
  build:
    name: Testing if
    runs-on: ubuntu-latest
    needs: [init]
#    if: ${{ needs.init.steps.vars.outputs.HAS_SECRET }}
    steps:
      - run: echo ${{ needs.init.outputs.output }}
