name: Test If

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  init:
    runs-on: ubuntu-latest    
    steps:
      - name: init vars
        id: vars
        shell: bash
        run: |
          unset HAS_SECRET
          if [-n $SECRET]; then HAS_SECRET='true' ; fi
          echo ::set-output name=HAS_SECRET_TOKEN::${HAS_SECRET}
  build:
    name: Testing if
    if: ${{ steps.vars.outputs.HAS_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
